### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by OctoCoder207** [AhamedBilal/ngx-photo-editor#12]
Hi, I've the following issues upon installation:

WARNING in ./node_modules/ngx-photo-editor/fesm5/ngx-photo-editor.js
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

I'm using the following:
"@angular/core": "7.2.15",
"typescript": "~3.1.3",
"ngx-photo-editor": "^0.3.5"

**Comment by AhamedBilal** [comment]
can you try to install now, updated the package peerDeps.
