### ISSUE TITLE
Event hook for closing the editor with cancel or option to hide cancel button

### ISSUE THREAD

**Issue by dh-gtheodoredis** [AhamedBilal/ngx-photo-editor#16]
Hello, currently there is no way to hide the cancel button or hook to the closing event after it is pressed. Either would be greatly helpful in 'resetting' the editor when using the imageURL attribute to load the editor.

**Comment by AhamedBilal** [comment]
Noted, ill add them in the next relese.

**Comment by AhamedBilal** [comment]
Fixed

**Comment by Outvites** [comment]
Hey @AhamedBilal , thanks for maintaining this library, can you please elaborate how to " hook to the closing event" ? I would like to reset the the input if user selects an image and clicks close instead of apply. how should one proceed?
