### ISSUE TITLE
imageChanedEvent NOT FOUND

### ISSUE THREAD

**Issue by sree6143** [AhamedBilal/ngx-photo-editor#20]
Error: Can't bind to 'imageChanedEvent' since it isn't a known property of 'ngx-photo-editor'.
1. If 'ngx-photo-editor' is an Angular component and it has 'imageChanedEvent' input, then verify that it is part of this module.s module.                                                                                                               nt to suppress this message.
2. If 'ngx-photo-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
                                                                                                                        $event)"
  <mat-card-content style="border:0px !important;">
    <ngx-photo-editor #profileImageEditor [ERROR ->][imageChanedEvent]="imageChangedEvent" (imageCropped)="imageCropped($event)"
    [aspectRatio]="4/3" ")

**Comment by AhamedBilal** [comment]
imageChangedEvent

**Comment by AhamedBilal** [comment]
ill fix the documentation

**Comment by Watchwolf** [comment]
I got the problem too, fix the doc please :)

Thank you for your work.

**Comment by AhamedBilal** [comment]
fixed
