### ISSUE TITLE
Error load css

### ISSUE THREAD

**Issue by rrkhissamov** [AhamedBilal/ngx-photo-editor#23]
File photo-editor.css add to style.css. Chrome console load photo-editor.css true.
Add NgxPhotoEditorService in lazyload module:
- Error: Module not found: Error: Expecting folder to folder mapping. "./photo-editor.css" should end with "/"

what could be the problem? Angular 14.0

Thank you

**Comment by AhamedBilal** [comment]
Did you import correctly?
