### ISSUE TITLE
resizeToHeight is not working correctly

### ISSUE THREAD

**Issue by ToWipf** [AhamedBilal/ngx-photo-editor#5]
if i use 
```
[resizeToHeight]="128"
[aspectRatio]="2/1"
```
or smaller, i always get an Image with 512x256

Is there a problem with small formats?

**Comment by AhamedBilal** [comment]
Issue fixed. You can now install the new version 0.3.3. Thanks for pointing the issue.

**Comment by ToWipf** [comment]
Thank you for the fast fix.
Working now
