### ISSUE TITLE
How to change button name of popup crop image?

### ISSUE THREAD

**Issue by bapdola304** [AhamedBilal/ngx-photo-editor#6]
Hi AhamedBilal team. How to I can change button name of popup crop image of your package?
This demo of my issue

![image](https://user-images.githubusercontent.com/43715437/105941621-6c17fa80-6090-11eb-9ae5-48df055f9fe7.png)

**Comment by AhamedBilal** [comment]
currently, there are no options for changing that. I'll add an option in the next release.

**Comment by AhamedBilal** [comment]
Added this options (applyBtnText, closeBtnText) refer documentation
