### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by sudeesh654** [AhamedBilal/ngx-photo-editor#7]
Style issues showing when use cropper
![img](https://user-images.githubusercontent.com/79838730/109480908-23de6480-7aa2-11eb-886b-0a010b13902f.png)

**Comment by shalvy** [comment]
ng-photo-editor, disturbes my icons
![Icons ](https://user-images.githubusercontent.com/26919655/115031735-caeb5400-9ec8-11eb-81a4-18f46effcb75.png)

**Comment by AhamedBilal** [comment]
I'll fix it ASAP. I think the problem is fontawesome.

**Comment by shalvy** [comment]
Thanks please do

**Comment by AhamedBilal** [comment]
Issue Fixed Install the new version.

**Comment by AhamedBilal** [comment]
What's your bootstrap version?

**Comment by sudeesh654** [comment]
^4.5.2

**Comment by shalvy** [comment]
all of a sudden I can't edit the picture, after adding file the window to
edit is no longer appearing, tries reinstalling the ngx-photo-editor
  , tried reinstalling the modules but it did not resolve the issue

**Comment by shalvy** [comment]
Hi AhamedBilal/ngx-photo-editor same issues reappeared again
