### ISSUE TITLE
Width of image

### ISSUE THREAD

**Issue by thiagogualberto** [AhamedBilal/ngx-photo-editor#8]
How do I get the width of an image?

**Comment by AhamedBilal** [comment]
[resizeToWidth]="500" -> 500 = 500px

**Comment by AhamedBilal** [comment]
u can also get the output image width and height from base64 output

**Comment by thiagogualberto** [comment]
> u can also get the output image width and height from base64 output


How can I do this?

**Comment by AhamedBilal** [comment]
https://stackoverflow.com/questions/17774928/js-get-image-width-and-height-from-the-base64-code

**Comment by thiagogualberto** [comment]
Thank you!
